### ISSUE TITLE
Angular RC4 Errors

### ISSUE THREAD

**Issue by payneBrandon** [jwasilgeo/angular2-esri-playground#11]
This doesn't seem to work with the latest Angular release candidate, 2.0.0-rc.4.  The application doesn't get past the loading screen, and console shows numerous 404 errors.  Any tips to get it running?

**Comment by jwasilgeo** [comment]
@payneBrandon I'm glad that you're interested in this and trying this example project out!

Since the last major changes were made in this repo, they were for 2.0.0-rc.1.  Since then, it looks like Angular2 has had some breaking changes in every other RC version along the way: https://github.com/angular/angular/blob/master/CHANGELOG.md

My quick guess is that it probably has sometime to do with the router.  Since I started with this, it seems like they change it just for fun, and frequently.

If you are interested in finding out what needs to change, I definitely welcome pull requests. :smile:  Otherwise, my plan was to wait until the first release of Angular2 and not chase down RC changes along the way.

**Comment by devtoil** [comment]
Removing 'rotation' (line 30) from the SceneView options in esri-scene-view.component.ts allowed the project to build for me.

**Comment by jwasilgeo** [comment]
Hey all, now that Angular2 is finally released, I'll be updating the code in this example repo soon and hopefully that'll show you an up-to-date working example without having to fight against previous RC versions.

**Comment by jwasilgeo** [comment]
I've updated everything to the new Angular 2 release.  Let me know if you have any feedback or questions for me!
