### ISSUE TITLE
Potentially bad Chrome warning

### ISSUE THREAD

**Issue by lax20attack** [jwasilgeo/angular2-esri-playground#13]
This can be reproduced using the current repository. Just open Synched-Views.

The following Chrome Console Warning has me a bit worried, and I would like to know if there are any plans to work around this. I am not sure exactly why this is being thrown.

> Invoking 'send()' on a sync XHR during microtask execution is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5647113010544640 for more details.

Thanks!

**Comment by jwasilgeo** [comment]
@lax20attack thank you for pointing this out!  This is most likely triggered by something that the Esri JSAPI 4.x is doing in that library's code.  I say this because I also see the same warning when browsing one of the JSAPI 4 samples with a `SceneView`:
https://developers.arcgis.com/javascript/latest/sample-code/get-started-sceneview/index.html

You are welcome to point this out to the team that is responsible for this at the bottom of those JSAPI docs pages using the "Feedback on this topic?" link.

**Comment by lax20attack** [comment]
@jwasilgeo, Thanks, I left feedback for Esri as you suggested.

It appears this was related to the SceneView. I have changed to use MapView instead, and am no longer seeing the warning.

**Comment by jwasilgeo** [comment]
👍

**Comment by lax20attack** [comment]
To follow up- Esri responded and mentioned ARCGis 4.1 does not have this issue. They were also kind enough to point out this appeared to be fixed with the latest Chrome, and Chrome will not deprecate this functionality. Thanks again!
