### ISSUE TITLE
Angular2 and ESRI 4 in Visual Studio

### ISSUE THREAD

**Issue by CraigAP** [jwasilgeo/angular2-esri-playground#6]
I, along with many other developers, use Visual Studio as my primary development tool. It would be so valuable to have a starter Visual Studio project that can be the basis for building apps that use the latest from ESRI and Angular. I've tried to create a Visual Studio 2015 project based on the code in this repository. It can be found at [https://github.com/CraigAP/Angular2MapStart.git]. It builds, but trying to run it results in JavaScript errors.

I had originally posted this in the Angular1 repository, but this is where it belongs.

**Comment by jwasilgeo** [comment]
@CraigAP now that I understand that you were interested in Angular 2 with Esri JSAPI, have you looked over the repo [Esri/esri-system-js](https://github.com/Esri/esri-system-js), and specifically these open issue discussions?
- https://github.com/Esri/esri-system-js/issues/6
- https://github.com/Esri/esri-system-js/issues/7

I think it might be worthwhile to (again) move your question/request over there to continue the conversation.  What do you think, @tomwayson?

**Comment by CraigAP** [comment]
Thanks, Jacob.  These look like good discussions.  I’m glad to see I’m not the only one having problems.  I don’t think my entry really adds anything except to say how important it is to make all this good stuff work in Visual Studio.

Craig

**Comment by tomwayson** [comment]
I think people should be using [Visual Studio Code](https://code.visualstudio.com/) instead of Visual Studio for front-end development, but that's just one man's opinion.

**Comment by CraigAP** [comment]
I took @tomwayson 's suggestion and looked at VS Code.  Looked very cool.  Downloaded, installed, installed the C# extension, opened my folder.  I don't have C# intellisense.  I've already spent hours trying to get somwhere with it.  It will take days to master it (maybe).  Other participants in this topic also speak of spending hours or days trying to get it ESRI 4.0 and Angular2 going.  Both of these frameworks are huge improvements over earlier versions.  I, for one, feel it's really important to base future development on using them.

I suggest @tomwayson  or @jwasilgeo, who both like VS code over VS Studio create a demo using it.  I think this is in ESRI's best interest.  It makes no sense for thousands of ESRI map developers to all spend days trying to do something that should not be so difficult.  I also suggest taking a survey of developers to see what tools they use.  My guess is that a very large number use Visual Studio for solid reasons including simple familiarity.  Part of the problem is that ESRI is happy if things run in the playground, Angular does not care too much if ESRI code works or not. Microsoft doesn't either.  What would be nice would be for all the parties to get together and find solutions.

Sorry for the rant, but I'm very frustrated.

**Comment by tomwayson** [comment]
@CraigAP 

I'm sorry that you didn't have a good experience with Visual Studio Code. I was hoping that Visual Studio Code would work as well for C# as it does for TypeScript.

I appreciate your thoughts re: the importance of having the JSAPI work well w/ Angular 2 and specifically in Visual Studio. Honestly, I have been surprised by how many developers are raising issues about this. 

As far as a demo, when I work on this repo, or [my own](https://github.com/tomwayson/angular2-esri-example/), I use Visual Studio Code and have no issues. So as long as you don't have to do any back-end C# development in the same IDE, it works.

These days I don't really do any back end coding (and if I do it's in node), I develop solely on a Mac, and since our DevSummit presentation have been working on a project that uses EmberJS for the front-end. So I'm not really the best person to demonstrate how to get this working in Visual Studio. @jwasilgeo?

I can't promise anything other than I will pass along your feedback to others here at Esri that are using our JSAPI with Angular 2. However, I don't know that any of those developers are specifically using Visual Studio, so it may be the case that the solution for this comes from the community. As @jwasilgeo mentioned above, the best thing to do at this time is to subscribe to the issues in the Esri/System-js repo:
- [Esri/esri-system-js#6](https://github.com/Esri/esri-system-js/issues/6)
- [Esri/esri-system-js#7](https://github.com/Esri/esri-system-js/issues/7)

Thank you for your feedback and patience.

**Comment by ajturner** [comment]
poke @nixta @alaframboise @andygup @patrickarlt in case this is useful for the GeoDev or Developers teams to look at supporting

**Comment by jwasilgeo** [comment]
@CraigAP @ajturner @tomwayson I'll close this one up for now since there have been some **really nice** updates to Esri/esri-system-js over the past few days that I think might cover this.

**Comment by CraigAP** [comment]
Ok, thanks.  I’ve just succeeded in getting a Visual Studio project going with Angular2 and ASPnetCore, and I’m now working on integrating your playground.  I see the esri-system-js is now 1.0.0-beta.0.  Sounds promising.

Craig
